project:
  type: website

website:
  page-navigation: true
  back-to-top-navigation: true
  title: "PEER Institute"
  site-url: "https://peerinstitute.org/"
  favicon: "/images/peer.png"
  open-graph: true
  navbar:
    title: PEER Institute
    background: primary
    search: true
    reader-mode: true
    logo: "/images/peer.png"

    right:
      - text: "PEER Model"
        href: model/index.qmd
      - text: "PEER Impacts"
        href: impacts.qmd
      - text: "Field Schools"
        href: schools/index.qmd
      - contact.qmd
    tools:
      - icon: journal-text
        href: https://handbook.zaposa.com/

  page-footer:
    center: "Built with [Quarto](https://quarto.org/) and hosted on [GitHub](https://github.com/esayre)."
    right:
      - icon: github
        href: https://github.com/esayre
      

 
format:
  html:
    toc: false
    theme: 
       light: 
         - yeti
       dark: 
         - superhero
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    fontsize: 12pt
    template-partials: 
      - title-block.html
    appendix-style: none
    enable-cssgrid: true
    page-layout: article
    grid:
      body-width: 1000px
      gutter-width: 25px
      margin-width: 90px
    css: styles.css

# Rendering choices
editor: source
freeze: auto
execute:
  echo: false

# Appearance choices
callout-appearance: simple
cap-location: top
fig-cap-location: bottom
reference-location: document #for footnotes, could be margin or document
citation-location: document #for citations
footnotes-hover: true # to hover over footnotes

