---
title: "Sample Field School"

title-block-banner: "images/rainbow.jpg"

page-layout: article
toc: false
suppress: true
tbl-cap-location: top
---

# Field School Learning Outcomes

::::: {.quarto-listing .quarto-listing-container-grid}
:::: {.list .grid .quarto-listing-cols-2}

:::{.g-col-1 .text-left}
Participants in this school will...
:::

:::{.g-col-1 .text-left}
* …develop and practice fundamental underlying skills and competencies in doing research, including “yes, and”, generative writing, collaboration skills, and other topics as related to specific workshops.
* …develop and make significant progress in planning their own research projects.
* …increase their self-efficacy in doing education research (and communicating research in English, as appropriate).
:::
::::
:::::

# Field School Structure and Coverage
A typical PEER field school takes participants through a development arc.  We start with developing research questions and workshop norms and progress through modules on research process and research ethics.  By midweek, participants have done substantial writing and development on their own projects, and we delve into methodological issues of collecting, reducing, and analyzing data from the perspective of noticing ideas (e.g. in classroom video, student free responses, or interviews) and regularizing them (e.g. through generative coding).  Near the end of the field school, we give deep collaborative feedback to participants through generative presentations of their own projects, and help them plan explicitly for the next six months of research and development work.

&nbsp;  
```{=HTML}
<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th>Online Kickoff</th>
      <th>Day 1</th>
      <th>Day 2</th>
      <th>Day 3</th>
      <th>Day 4</th>
      <th>Day 5</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Field School Welcome
        </div>
      </td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Elevator Talks
        </div>
      </td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Research Process Models
        </div>
      </td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Noticing: Data in Observations
        </div>
      </td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Generative Presentations
        </div>
      </td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Generative Presentations
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Refining Research Interests
        </div>
      </td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Collaboration Ethics
        </div>
      </td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Theory
        </div>
      </td>
      <td></td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Research Methods Suite
        </div>
      </td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Authorship
        </div>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Data & Access
        </div>
      </td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Ethics of Human Research
        </div>
      </td>
      <td></td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          Generative Presentations
        </div>
      </td>
      <td>
        <div class="card bg-info text-black p-3 rounded">
          What Comes Next?
        </div>
      </td>
    </tr>
  </tbody>
</table>
```
&nbsp;  

PEER field schools are responsive to the needs of participants. In addition to the typical coverage outlined above, we also have developed additional modules to enrich their learning and meet their professional development needs. Additional modules include:

&nbsp;  

* Research communication: talking to skeptical colleagues about your research; making beautiful posters; conducting literature reviews and situating your work in a scholarly conversation; how, when, and where to publish your work.
* Research methods: autoethnography; conducting interviews; analyzing classroom data; fundamentals of descriptive statistics; getting started in developing a survey; design-based research projects
* Research collaboration: building robust collaborations; advising undergraduates in research projects
* Research life: personal stories around becoming a researcher, balancing research and other professional activities, and balancing professional activities with parenting and being a full human.

Some field schools are longer or shorter. Each field school is tuned to the needs of the participants, who also receive materials related to each module such as slides, handouts, exercises, and readings.

::::: {.quarto-listing .quarto-listing-container-grid}
:::: {.list .grid .quarto-listing-cols-2}

:::{.g-col-1 .text-center}
# I want to host a Field School.

Fabulous! [Contact the directors](contact.qmd) to learn about how.
:::

:::{.g-col-1 .text-center}
# I want to join a field school.

Exciting! Check out [upcoming field schools](schools/index.qmd).
:::
::::
:::::