---
title: "PEER-Chicago (Winter 2023) Syllabus"
---

<!-- START Syllabus Accordion (Outer) -->
::::::::::::{.accordion id="accordionSyllabus"}

<!-- START Syllabus Accordion -> Item 1 -->
:::::::::::{.accordion-item}

<!-- START Syllabus Accordion -> Item 1 -> Header -->
::::::::::{.accordion-header id="headingLogistics"}

:::::::::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseLogistics" aria-expanded="false" aria-controls="collapseLogistics"}

## Logistics

:::::::::
::::::::::
<!-- END Syllabus Accordion -> Item 1 -> Header -->

<!-- START Syllabus Accordion -> Item 1 -> Body -->
::::::::::{.accordion-collapse .collapse id="collapseLogistics" aria-labelledby="headingLogistics" data-bs-parent="#accordionSyllabus"}
:::::::::{.accordion-body}

<!-- START Syllabus Accordion -> Item 1 -> Body -> 2-col text block -->
:::::::: {.quarto-listing .quarto-listing-container-grid}
::::::: {.list .grid .quarto-listing-cols-2}

::::::{.g-col-1 .text-left}

## Schedule

All sessions will be held in Byrne Hall (2219 N Kenmore Ave)

* Virtual Kickoff: Thursday, Nov. 30, Time: 3:00-4:30pm (Central Time) [Zoom link](https://ksu.zoom.us/j/93378295978?pwd=Q3cwY0lvaTQrRURlYnRZYmhsMDVWUT09).
* Thursday, Dec. 14, 3:00-6:00pm: Opening session
    * Optional dinner: [Homeslice](https://www.happycamper.pizza/homeslice/) (you will be able to purchase food/drink and we will have reserved seating in their heated, outdoor patio)
* Friday, Dec. 15: 9:00am-4:00pm (breakfast at 8:00am)
* Saturday, Dec. 16: 9:00am-4:00pm (breakfast at 8:00am)
* Sunday, Dec. 17: 9:00am-1:00pm (breakfast at 8:00am, ends with closing lunch)

::::::

::::::{.g-col-1 .text-left}

## Links

:::::{zoom-button}
[Zoom Link for Virtual Kickoff](https://ksu.zoom.us/j/93378295978?pwd=Q3cwY0lvaTQrRURlYnRZYmhsMDVWUT09){.btn role="button" .btn-primary .rounded-pill}
:::::

&nbsp;  

:::::{slack-button}
[Slack Link](https://join.slack.com/t/peer-pbe2329/shared_invite/zt-25p9wvity-kIugoURsaSxRvPnFUQsUwQ){.btn role="button" .btn-primary .rounded-pill}
:::::

&nbsp;  

:::::{peer-button}
[PEER Main Site](https://www.peerinstitute.org/){.btn role="button" .btn-primary .rounded-pill}
:::::

&nbsp;  

:::::{contact-facilitator-button}
[Contact Lead Facilitator](mailto:esayre@gmail.com){.btn role="button" .btn-primary .rounded-pill}
:::::

&nbsp;  

:::::{contact-host-button}
[Contact Local Host](mailto:mkustus1@depaul.edu){.btn role="button" .btn-primary .rounded-pill}
::::: 

::::::
:::::::
::::::::
<!-- END Syllabus Accordion -> Item 1 -> Body -> 2-col text block -->

<!-- START Syllabus Accordion -> Item 1 -> Body -> Logistics Accordion (Inner 1) -->
::::::{.accordion id="accordionLogistics"}

<!-- START Logistics Accordion -> Item 1 -->
:::::{.accordion-item}

<!-- START Logistics Accordion -> Item 1 -> Header -->
::::{.accordion-header id="headingWifi"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseWifi" aria-expanded="false" aria-controls="collapseWifi"}

### Wifi access on DePaul's campus

:::
::::
<!-- END Logistics Accordion -> Item 1 -> Header -->

<!-- START Logistics Accordion -> Item 1 -> Body -->
::::{.accordion-collapse .collapse id="collapseWifi" aria-labelledby="headingWifi" data-bs-parent="#accordionLogistics"}
:::{.accordion-body}

* If you have eduroam, this is the easiest option.
* If you do not have eduroam, follow the instructions for [Conference Guest WiFi Setup](https://depaul.service-now.com/sp?id=kb_article_view&sysparm_article=KB0010094&sys_kb_id=4cd569fb1bef05108e0e337cdc4bcbf8&spa=1) using the Conference ID: **peer2023**

:::
::::
<!-- END Logistics Accordion -> Item 1 -> Body -->

:::::
<!-- END Logistics Accordion -> Item 1 -->

<!-- START Logistics Accordion -> Item 2 -->
:::::{.accordion-item}

<!-- START Logistics Accordion -> Item 2 -> Header -->
::::{.accordion-header id="headingHousing"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseHousing" aria-expanded="false" aria-controls="collapseHousing"}

### Housing

:::
::::
<!-- END Logistics Accordion -> Item 2 -> Header -->

<!-- START Logistics Accordion -> Item 2 -> Body -->
::::{.accordion-collapse .collapse id="collapseHousing" aria-labelledby="headingHousing" data-bs-parent="#accordionLogistics"}
:::{.accordion-body}

Housing is provided at [City Suites Hotel](https://www.chicagocitysuites.com/) (933 West Belmont Ave). If there are issues with your reservation, please contact Maria Lipan at [mlipan@charlestownehotels.com](mailto:mlipan@charlestownehotels.com) with the subject DePaul Group Confirmation.

&nbsp;  

Check-in is at 3pm, but the hotel does have a storage room for any luggage, so you can drop off your bags when you arrive even if it is before 3pm.

:::
::::
<!-- END Logistics Accordion -> Item 2 -> Body -->

:::::
<!-- END Logistics Accordion -> Item 2 -->

<!-- START Logistics Accordion -> Item 3 -->
:::::{.accordion-item}

<!-- START Logistics Accordion -> Item 3 -> Header -->
::::{.accordion-header id="headingParking"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseParking" aria-expanded="false" aria-controls="collapseParking"}

### Parking

:::
::::
<!-- END Logistics Accordion -> Item 3 -> Header -->

<!-- START Logistics Accordion -> Item 3 -> Body -->
::::{.accordion-collapse .collapse id="collapseParking" aria-labelledby="headingParking" data-bs-parent="#accordionLogistics"}
:::{.accordion-body}

* If you are flying into Chicago, both O’Hare and Midway airports are accessible and ~45-70 min from DePaul on CTA and ~25-45 min by car. Chicago has rideshare options (Uber and Lyft) as well as several reputable taxi companies.
* There are two parking lots close to Byrne Hall that can be used (we will provide vouchers that you will use when you exit the garage)
    * 2331 N Sheffield Ave
    * 2330 N Clifton Ave
* If you are staying at the hotel, there is a parking garage right around the corner from the hotel that offers public parking for $30 per night. You can pick up a hotel parking pass when you arrive at the hotel.

:::
::::
<!-- END Logistics Accordion -> Item 3 -> Body -->

:::::
<!-- END Logistics Accordion -> Item 3 -->

<!-- START Logistics Accordion -> Item 4 -->
:::::{.accordion-item}

<!-- START Logistics Accordion -> Item 4 -> Header -->
::::{.accordion-header id="headingDirections"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseDirections" aria-expanded="false" aria-controls="collapseDirections"}

### Directions between DePaul and hotel on CTA

:::
::::
<!-- END Logistics Accordion -> Item 4 -> Header -->

<!-- START Logistics Accordion -> Item 4 -> Body -->
::::{.accordion-collapse .collapse id="collapseDirections" aria-labelledby="headingDirections" data-bs-parent="#accordionLogistics"}
:::{.accordion-body}

We will provide a 7-day Ventra/CTA pass to get to/from DePaul for the field school using the CTA trains. You can use this pass on any CTA train or bus for 7 days after you first swipe it.

&nbsp;  

Directions from hotel to DePaul on CTA

&nbsp;  

* At the Belmont station, tap your pass for entry and go to the southbound platform (right) and get on any train that stops here.
    * Red line (to 95th): 1 stop to Fullerton
    * Brown line or Purple line (to Loop): 3 stops to Fullerton
* Once you exist the train, Byrne hall is one block west and two blocks south of the station.

Directions from DePaul to hotel on CTA

&nbsp;  

* At the Fullerton station, tap your pass for entry and go to the northbound platform (left) and get on any train that stop here.
    * Red line (towards Howard): 1 stop to Belmont
    * Brown line (to Howard) or Purple line (to Linden): 3 stops to Belmont

:::
::::
<!-- END Logistics Accordion -> Item 4 -> Body -->

:::::
<!-- END Logistics Accordion -> Item 4 -->

<!-- START Logistics Accordion -> Item 5 -->
:::::{.accordion-item}

<!-- START Logistics Accordion -> Item 5 -> Header -->
::::{.accordion-header id="headingFood"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseFood" aria-expanded="false" aria-controls="collapseFood"}

### Food

:::
::::
<!-- END Logistics Accordion -> Item 5 -> Header -->

<!-- START Logistics Accordion -> Item 5 -> Body -->
::::{.accordion-collapse .collapse id="collapseFood" aria-labelledby="headingFood" data-bs-parent="#accordionLogistics"}
:::{.accordion-body}

* We will be providing breakfast, lunch, and snacks on-site during the workshops. If you have dietary constraints, please contact Mary Ann Quinn ([mquinn22@depaul.edu](mailto:mquinn22@depaul.edu)).
* On Thursday, we will have an optional dinner at [Homeslice](https://www.happycamper.pizza/homeslice/) to help build community. You will be able to purchase your own food/drink and we will have a reserved seating area in their heated, outdoor patio.
* On other nights, you will be responsible for dinners; there are many restaurants within easy walking distance of both DePaul (see [Dining options near DePaul University, Lincoln Park](https://docs.google.com/document/d/1T4lULBxdB1bgJNQgfkwVe0S09zk0BVBrrOJEDMpPK6M/edit?usp=sharing)) and the hotel. We will provide opportunities for you to coordinate with each other around meals.

:::
::::
<!-- END Logistics Accordion -> Item 5 -> Body -->

:::::
<!-- END Logistics Accordion -> Item 5 -->

::::::
<!-- END Syllabus Accordion -> Item 1 -> Body -> Logistics Accordion (Inner 1) -->

:::::::
::::::::
:::::::::
:::::::::{.accordion-item}
::::::::{.accordion-header id="headingMaterials"}
:::::::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseMaterials" aria-expanded="false" aria-controls="collapseMaterials"}

## Field School Materials

:::::::
::::::::
::::::::{.accordion-collapse .collapse id="collapseMaterials" aria-labelledby="headingMaterials" data-bs-parent="#accordionSyllabus"}
:::::::{.accordion-body}

<!-- START Syllabus Accordion -> Item 2 -> Body -> Materials Accordion (Inner 2) -->
::::::{.accordion id="accordionMaterials"}

<!-- START Materials Accordion -> Item 1 -->
:::::{.accordion-item}

<!-- START Materials Accordion -> Item 1 -> Header -->
::::{.accordion-header id="headingBeforeVirtual"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseBeforeVirtual" aria-expanded="false" aria-controls="collapseBeforeVirtual"}

### To be completed before Virtual Kickoff

:::
::::
<!-- END Materials Accordion -> Item 1 -> Header -->

<!-- START Materials Accordion -> Item 1 -> Body -->
::::{.accordion-collapse .collapse id="collapseBeforeVirtual" aria-labelledby="headingBeforeVirtual" data-bs-parent="#accordionMaterials"}
:::{.accordion-body}

* Complete evaluation pre-survey
* Read [Writing as a generative process](https://handbook.zaposa.com/articles/generative-writing/) and spend some time preparing yourself for generative writing.
* Introduce yourself on Slack.

:::
::::
<!-- END Materials Accordion -> Item 1 -> Body -->

:::::
<!-- END Materials Accordion -> Item 1 -->

<!-- START Materials Accordion -> Item 2 -->
:::::{.accordion-item}

<!-- START Materials Accordion -> Item 2 -> Header -->
::::{.accordion-header id="headingBeforeInPerson"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseBeforeInPerson" aria-expanded="false" aria-controls="collapseBeforeInPerson"}

### To be completed before in-person FIeld School

:::
::::
<!-- END Materials Accordion -> Item 2 -> Header -->

<!-- START Materials Accordion -> Item 2 -> Body -->
::::{.accordion-collapse .collapse id="collapseBeforeInPerson" aria-labelledby="headingBeforeInPerson" data-bs-parent="#accordionMaterials"}
:::{.accordion-body}

* Read Data and access to prepare for our discussion of common data types.
* Read Generative Presentations to prepare for your own generative presentation, and complete the survey on that page to sign up.  
  The password is “GenerativePresentations”

:::
::::
<!-- END Materials Accordion -> Item 2 -> Body -->

:::::
<!-- END Materials Accordion -> Item 2 -->

<!-- START Materials Accordion -> Item 3 -->
:::::{.accordion-item}

<!-- START Materials Accordion -> Item 3 -> Header -->
::::{.accordion-header id="headingSlides"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseSlides" aria-expanded="false" aria-controls="collapseSlides"}

### Field School Slides and Handouts

:::
::::
<!-- END Materials Accordion -> Item 3 -> Header -->

<!-- START Materials Accordion -> Item 3 -> Body -->
::::{.accordion-collapse .collapse id="collapseSlides" aria-labelledby="headingSlides" data-bs-parent="#accordionMaterials"}
:::{.accordion-body}

* TBD

:::
::::
<!-- END Materials Accordion -> Item 3 -> Body -->

:::::
<!-- END Materials Accordion -> Item 3 -->

<!-- START Materials Accordion -> Item 4 -->
:::::{.accordion-item}

<!-- START Materials Accordion -> Item 4 -> Header -->
::::{.accordion-header id="headingAfter"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseAfter" aria-expanded="false" aria-controls="collapseAfter"}

### To be completed after the Field School

:::
::::
<!-- END Materials Accordion -> Item 4 -> Header -->

<!-- START Materials Accordion -> Item 4 -> Body -->
::::{.accordion-collapse .collapse id="collapseAfter" aria-labelledby="headingAfter" data-bs-parent="#accordionMaterials"}
:::{.accordion-body}

* Complete evaluation post-survey
* Continue to engage with each other on Slack (including starting channels).

:::
::::
<!-- END Materials Accordion -> Item 4 -> Body -->

:::::
<!-- END Materials Accordion -> Item 4 -->

::::::
<!-- END Syllabus Accordion -> Item 2 -> Body -> Materials Accordion (Inner 2) -->

:::::::
::::::::
:::::::::
:::::::::{.accordion-item}
::::::::{.accordion-header id="headingModules"}
:::::::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseModules" aria-expanded="false" aria-controls="collapseModules"}
## Modules and Learning Outcomes
:::::::
::::::::
::::::::{.accordion-collapse .collapse id="collapseModules" aria-labelledby="headingModules" data-bs-parent="#accordionSyllabus"}
:::::::{.accordion-body}

<!-- START Syllabus Accordion -> Item 1 -> Body -> Modules Accordion (Inner 1) -->
::::::{.accordion id="accordionModules"}

<!-- START Modules Accordion -> Item 1 -->
:::::{.accordion-item}

<!-- START Modules Accordion -> Item 1 -> Header -->
::::{.accordion-header id="headingVirtual"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseVirtual" aria-expanded="false" aria-controls="collapseVirtual"}

### Virtual Kickoff: Thursday, Nov. 30, 3:00-4:30pm (Central Time)

:::
::::
<!-- END Modules Accordion -> Item 1 -> Header -->

<!-- START Modules Accordion -> Item 1 -> Body -->
::::{.accordion-collapse .collapse id="collapseVirtual" aria-labelledby="headingVirtual" data-bs-parent="#accordionModules"}
:::{.accordion-body}

### Field School Welcome

Provides an introduction to PEER goals and principles, as well as to facilitators and other participants.

&nbsp;  

#### Participants will be able to…

&nbsp;  

…articulate the norms and goals of the field school  

…identify their facilitator team and who to contact about which issues  

&nbsp;  

___

### Refining Research interests

Participants work on refining their research interests by learning about and practicing fundamental research skills, including generative writing, “yes, and”, reflection and refinement.

&nbsp;  

#### Participants will be able to…

&nbsp;  

… identify their research interests  

… refine their research interests into a question  

… practice generative writing  

… practice playing yes, and  

&nbsp;  

___

:::
::::
<!-- END Modules Accordion -> Item 1 -> Body -->

:::::
<!-- END Modules Accordion -> Item 1 -->

<!-- START Modules Accordion -> Item 2 -->
:::::{.accordion-item}

<!-- START Modules Accordion -> Item 2 -> Header -->
::::{.accordion-header id="headingThursday"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseThursday" aria-expanded="false" aria-controls="collapseThursday"}

### Thursday, Dec. 14: 3:00-6:00pm

:::
::::
<!-- END Modules Accordion -> Item 2 -> Header -->

<!-- START Modules Accordion -> Item 2 -> Body -->
::::{.accordion-collapse .collapse id="collapseThursday" aria-labelledby="headingThursday" data-bs-parent="#accordionModules"}
:::{.accordion-body}

### Field school Welcome

Provides a recap of PEER goals and principles, as well as re-introduction to facilitators and other participants.

&nbsp;  

#### Participants will be able to…

…articulate the norms and goals of the field school  

…identify their facilitator team and who to contact about which issues  


&nbsp;  

___

### Collaboration ethics

Participants role-play and discuss scenarios involving ethical issues in research collaborations.

&nbsp;  

#### Participants will be able to…

…recognize ethical issues in research collaborations  

…identify ways to address ethical issues before/after they arise  


&nbsp;  

___

### Elevator pitches

Discussion of principles for giving elevator pitches and possible structures using examples. Contains two rounds of using 2-minute elevator pitches to seed 5-min discussions between pairs of participants.

&nbsp;  

#### Participants will be able to…

…articulate principles for elevator pitches  

…concisely articulate their research interests/project  

…articulate various goals for different elevator pitches  

…see how elevator pitches seed productive discussions (not monologues)  


&nbsp;  

___

### Collect Burning Questions
Participants articulate the questions that are most relevant to their needs in the moment and practice interaction norms to prioritize questions

&nbsp;  

___

:::
::::
<!-- END Modules Accordion -> Item 2 -> Body -->

:::::
<!-- END Modules Accordion -> Item 2 -->

<!-- START Modules Accordion -> Item 3 -->
:::::{.accordion-item}

<!-- START Modules Accordion -> Item 3 -> Header -->
::::{.accordion-header id="headingFriday"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseFriday" aria-expanded="false" aria-controls="collapseFriday"}

### Friday, Dec. 15, 9:00am-4:00pm

:::
::::
<!-- END Modules Accordion -> Item 3 -> Header -->

<!-- START Modules Accordion -> Item 3 -> Body -->
::::{.accordion-collapse .collapse id="collapseFriday" aria-labelledby="headingFriday" data-bs-parent="#accordionModules"}
:::{.accordion-body}

### Answering Burning Questions

Facilitators address previously collected participant burning questions. Learning outcomes are emergent and heavily dependent on participants' questions.

&nbsp;   

___

### Data Types and Access

Participants discuss common data types and how to match data and research questions using two case studies as touchstone examples.

&nbsp;  

#### Participants will be able to…

…identify when several common data types are a good/poor choice  

…match your research question and context to appropriate data types  

&nbsp;  

___

### Research process models

Discussion of models for the research process and implications for practice, specifically contrasting a stage model with a parallel process model.

&nbsp;  

#### Participants will be able to…

…articulate the differences between a stage model for research and a parallel process model and implications for practice  

&nbsp;  

___

### Ethics for Human Subjects Research

Discussion of the ethics of doing research with human subjects in the context of education research centered around role-playing and discussing real case-study scenarios.

&nbsp;  

#### Participants will be able to…

…recognize ethical issues in research with human subjects that are common in educational research  

…identify ways to address ethical issues before/after they arise  

&nbsp;  

___

:::
::::
<!-- END Modules Accordion -> Item 3 -> Body -->

:::::
<!-- END Modules Accordion -> Item 3 -->

<!-- START Modules Accordion -> Item 4 -->
:::::{.accordion-item}

<!-- START Modules Accordion -> Item 4 -> Header -->
::::{.accordion-header id="headingSaturday"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseSaturday" aria-expanded="false" aria-controls="collapseSaturday"}

### Saturday, Dec. 16: 9:00am-4:00pm

:::
::::
<!-- END Modules Accordion -> Item 4 -> Header -->

<!-- START Modules Accordion -> Item 4 -> Body -->
::::{.accordion-collapse .collapse id="collapseSaturday" aria-labelledby="headingSaturday" data-bs-parent="#accordionModules"}
:::{.accordion-body}

### Answering Burning Questions

Facilitators address previously collected participant burning questions. Learning outcomes are emergent and heavily dependent on participants' questions.

&nbsp;   

___

### Generative Presentations

A participant presents their project and asks for targeted feedback and  the group plays “yes and” with their project.

&nbsp;  

#### Participants will be able to…

…present a project for intense feedback from facilitators and other participants  

…articulate the character of the feedback that will be most helpful  

…give and receive focused feedback on a specific project  

&nbsp;  

___

### Theory

Discussion of what is theory for and how it can be used to shape research questions, including an organizing framework for thinking about theory.

&nbsp;  

#### Participants will be able to…

….identify categories of theories by what entities are the subject of your research  

…identify appropriate research questions for each kind of entity  

…match your research question and context to the appropriate category of theory  

… know where to find theories and how to read papers for theory.  

&nbsp;  

___

### Collect Burning Questions

Participants articulate the questions that are most relevant to their needs in the moment and practice interaction norms to prioritize questions

&nbsp;  

___
:::
::::
<!-- END Modules Accordion -> Item 4 -> Body -->

:::::
<!-- END Modules Accordion -> Item 4 -->

<!-- START Modules Accordion -> Item 5 -->
:::::{.accordion-item}

<!-- START Modules Accordion -> Item 5 -> Header -->
::::{.accordion-header id="headingSunday"}
:::{.accordion-button .collapsed type="button" data-bs-toggle="collapse" data-bs-target="#collapseSunday" aria-expanded="false" aria-controls="collapseSunday"}

### Sunday, Dec. 17: 9:00am-1:00pm

:::
::::
<!-- END Modules Accordion -> Item 5 -> Header -->

<!-- START Modules Accordion -> Item 5 -> Body -->
::::{.accordion-collapse .collapse id="collapseSunday" aria-labelledby="headingSunday" data-bs-parent="#accordionModules"}
:::{.accordion-body}

### Answering Burning Questions

Facilitators address previously collected participant burning questions. Learning outcomes are emergent and heavily dependent on participants' questions.

&nbsp;   

___

### Generative Presentations

A participant presents their project and asks for targeted feedback and  the group plays “yes and” with their project.

&nbsp;  

#### Participants will be able to…

…present a project for intense feedback from facilitators and other participants  

…articulate the character of the feedback that will be most helpful  

…give and receive focused feedback on a specific project  

&nbsp;  

___

### What comes next

Includes a recap of what was accomplished during the field school and generative writing/planning for the future at different time scales.

&nbsp;  

#### Participants will be able to…

…be able to articulate the progress made during the field school  

…have a concrete plan for moving forward on their research project   

&nbsp;  

___

### Debrief & Closing

Participants provide communal, collective feedback on the process, program, and personal aspects of PEER.

&nbsp;  

___

:::
::::
<!-- END Modules Accordion -> Item 5 -> Body -->

:::::
<!-- END Modules Accordion -> Item 5 -->

::::::
<!-- END Syllabus Accordion -> Item 1 -> Body -> Modules Accordion (Inner 1) -->

:::::::
::::::::
:::::::::
::::::::::