---
title: "Sample Field School"

title-block-banner: "/images/rainbow.jpg"

page-layout: article
toc: false
suppress: true
tbl-cap-location: top
---

{{< include ../_prefix.qmd >}}


PEER enhances the professional growth of participants and changes career trajectories.  Our comprehensive professional development covers project design, management, mentoring, communication, and understanding community values. This 'full stack' of activities builds your research abilities.  No matter where you are in your education research journey, we'll take you to the next step. 

# Field School Learning Outcomes

## Learning outcomes

Participants in the field school will... 

* ... develop and practice fundamental underlying skills and competencies in doing research, including “yes, and”, generative writing, collaboration skills, and other topics as related to specific workshops
* ... develop and make significant progress in planning their own research projects
* ... increase their self-efficacy in doing education research
* ... build a community for supporting their education research

# Field School Structure and Coverage

PEER's development arc will take you through developing your research question, choosing theory and methods, and refining your research design to be resilient to unexpected developments.  You will learn concrete skills in research communication and productivity.  You will receive deep feedback on your project throughout the field school, and interact extensively with your co-participants to improve their projects and network together. 

&nbsp;  

```{=HTML}
<div style="overflow-x:auto;">
  <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th>Online Kickoff</th>
        <th>Day 1</th>
        <th>Day 2</th>
        <th>Day 3</th>
        <th>Day 4</th>
        <th>Day 5</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Field School Welcome
          </div>
        </td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Elevator Talks
          </div>
        </td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Research Process Models
          </div>
        </td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Noticing: Data in Observations
          </div>
        </td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Generative Presentations
          </div>
        </td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Generative Presentations
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Refining Research Interests
          </div>
        </td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Collaboration Ethics
          </div>
        </td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Theory
          </div>
        </td>
        <td></td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Research Methods Suite
          </div>
        </td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Authorship
          </div>
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Data & Access
          </div>
        </td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Ethics of Human Research
          </div>
        </td>
        <td></td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            Generative Presentations
          </div>
        </td>
        <td>
          <div class="card bg-info text-black p-3 rounded">
            What Comes Next?
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>
```
  

PEER field schools are responsive to the needs of participants. In addition to the typical coverage outlined above, we also have developed additional modules to enrich their learning and meet their professional development needs. Additional modules include:


* Research communication: talking to skeptical colleagues about your research; making beautiful posters; conducting literature reviews and situating your work in a scholarly conversation; how, when, and where to publish your work.
* Research methods: autoethnography; conducting interviews; analyzing classroom data; fundamentals of descriptive statistics; getting started in developing a survey; design-based research projects
* Research collaboration: building robust collaborations; advising undergraduates in research projects
* Research life: personal stories around becoming a researcher, balancing research and other professional activities, and balancing professional activities with parenting and being a full human.

Some field schools are longer or shorter. Each field school is tuned to the needs of the participants, who also receive materials related to each module such as slides, handouts, exercises, and readings.

# Who Should Attend?
 
PEER targets a broad diversity of experience and interest in discipline-based education research (DBER). PEER field schools are appropriate for:

* Faculty not currently engaged in DBER but interested in learning about theories and methodologies for possible future research
* Current DBER researchers looking to build or broaden their network of collaborators and engage in generative discussions about existing and new projects
* Graduate students or postdoctoral researchers who want to learn more about DBER project management and building a successful research program
* Faculty at teaching-focused universities interested in using research methodology to improve or assess their teaching and/or publish in Scholarship of Teaching & Learning

However, each field school has its own admissions requirements and focus.  

# What do we do?

### PEER builds core competencies in education research

 PEER enhances the professional growth of participants and changes career trajectories.  Our comprehensive professional development covers project design, management, mentoring, communication, and understanding community values. This 'full stack' of activities enhances research abilities.  We focus on the participants' interests and projects, fostering motivation and improving success chances.  

### Community Building and Networking

PEER promotes peer feedback and community foundation, providing a sense of inclusion in the DBER field and fostering research identity. The networking opportunities at PEER kickstart collaborations and expand professional networks. PEER supports participants from all STEM disciplines, and we focus on emerging education researchers, whatever their career level.  

### PEER builds academic currency

 Our support includes guiding participants in writing, a key element of academic research. PEER engagement leads to numerous publications, grant proposals, and successful tenure & promotion portfolios.  These publications span several years, suggesting PEER's lasting impact on participants’ professional trajectories.


`r invitation.cards(c("hosting", "upcoming"))`

